blank_issues_enabled: false
contact_links:
  - name: Discord
    about: You can join the discussions on Discord.
    url: https://l.devwtf.in/plura-dc
  - name: Twitter
    about: You can follow us on Twitter.
    url: https://x.com/plexy_ai